package com.tencent.mobileqq.transfile;

import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;

public class FileMsg {
    public static final int STATUS_FILE_EXPIRED = 5002;
    public static final int STATUS_FILE_TRANSFERING = 5000;
    public static final int STATUS_FILE_UNEXSIT = 5003;
    public static final int STATUS_FILE_UNSAFE = 5001;
    public static final int STATUS_FORWARD_WAIT = 4001;
    public static final int STATUS_PLAY_RECV_PROCESS_KILL = 2009;
    public static final int STATUS_PTT_VOICE_CHANGING = 7000;
    public static final int STATUS_RECV_CANCEL = 2004;
    public static final int STATUS_RECV_ERROR = 2005;
    public static final int STATUS_RECV_FINISHED = 2003;
    public static final int STATUS_RECV_PAUSE = 2007;
    public static final int STATUS_RECV_PREPARED = 2008;
    public static final int STATUS_RECV_PROCESS = 2002;
    public static final int STATUS_RECV_REQUEST = 2000;
    public static final int STATUS_RECV_SPACE_ERROR = 2006;
    public static final int STATUS_RECV_START = 2001;
    public static final int STATUS_SEND_AND_SAVE_FINISHED = 1008;

    public static final int STATUS_SEND_COMPRESS = 998;
    public static final int STATUS_SEND_PREPARE = 999;
    public static final int STATUS_SEND_REQUEST = 1000;
    public static final int STATUS_SEND_START = 1001;
    public static final int STATUS_SEND_PROCESS = 1002;
    public static final int STATUS_SEND_FINISHED = 1003;
    public static final int STATUS_SEND_CANCEL = 1004;
    public static final int STATUS_SEND_ERROR = 1005;
    public static final int STATUS_PAUSE = 1006;
    public static final int STATUS_UPLOAD_FINISHED = 1007;


    public static final int STATUS_VERIFY_ERROR = 3002;
    public static final int STATUS_VERIFY_REQUIRE = 3000;
    public static final int STATUS_VERIFY_SUCCESS = 3001;

    public static final int TRANSFILE_TYPE_ASSISTANT = 327697;
    public static final int TRANSFILE_TYPE_BASE_DYNAMIC_AVATAR_BIG = 36;
    public static final int TRANSFILE_TYPE_BASE_DYNAMIC_AVATAR_MEDIUM = 37;
    public static final int TRANSFILE_TYPE_BASE_DYNAMIC_AVATAR_SMALL = 38;
    public static final int TRANSFILE_TYPE_BASE_STATIC_AVATAR = 48;
    public static final int TRANSFILE_TYPE_BDH_COMMON_UP = 24;
    public static final int TRANSFILE_TYPE_BULUO_AUDIO_SILK = 25;
    public static final int TRANSFILE_TYPE_C2B_UPLOAD_FILE = 34;
    public static final int TRANSFILE_TYPE_CIRCLE = 131077;
    public static final int TRANSFILE_TYPE_EXTEND_FRIEND_AVATAR = 68;
    public static final int TRANSFILE_TYPE_EXTEND_FRIEND_PHOTO_WALL = 67;
    public static final int TRANSFILE_TYPE_EXTEND_FRIEND_SOUND = 23;
    public static final int TRANSFILE_TYPE_FILE = 0;
    public static final int TRANSFILE_TYPE_FRESH_NEWS_PHOTO = 21;
    public static final int TRANSFILE_TYPE_FRIEND_AVATAR = 22;
    public static final int TRANSFILE_TYPE_HOMEWORK_AUDIO_SILK = 65;
    public static final int TRANSFILE_TYPE_JS_PTT = 32;
    public static final int TRANSFILE_TYPE_LIGHT_VIDEO = 327689;
    public static final int TRANSFILE_TYPE_MAP = 65536;
    public static final int TRANSFILE_TYPE_MULTIMSG = 131078;
    public static final int TRANSFILE_TYPE_NEARBY_ALUMNI = 131080;
    public static final int TRANSFILE_TYPE_NEARBY_AUTH_THUMB = 64;
    public static final int TRANSFILE_TYPE_NEARBY_DYNAMIC_AVATAR_BIG = 39;
    public static final int TRANSFILE_TYPE_NEARBY_DYNAMIC_AVATAR_MEDIUM = 40;
    public static final int TRANSFILE_TYPE_NEARBY_DYNAMIC_AVATAR_SMALL = 41;
    public static final int TRANSFILE_TYPE_NEARBY_PEOPLE_PHOTO_WALL = 8;
    public static final int TRANSFILE_TYPE_OCR = 57;
    public static final int TRANSFILE_TYPE_PA_AUDIO = 33;
    public static final int TRANSFILE_TYPE_PERSONALITY_LABEL_PHOTO_WALL = 56;
    public static final int TRANSFILE_TYPE_PIC = 1;
    public static final int TRANSFILE_TYPE_PIC_EMO = 65538;
    public static final int TRANSFILE_TYPE_PIC_THUMB = 65537;
    public static final int TRANSFILE_TYPE_PISMA = 49;
    public static final int TRANSFILE_TYPE_PROFILE_COVER = 35;
    public static final int TRANSFILE_TYPE_PTT = 2;
    public static final int TRANSFILE_TYPE_PTT_SLICE_TO_TEXT = 327696;
    public static final int TRANSFILE_TYPE_QQHEAD_PIC = 131074;
    public static final int TRANSFILE_TYPE_RAWPIC = 131075;
    public static final int TRANSFILE_TYPE_SCRIBBLE_DATA = 262153;
    public static final int TRANSFILE_TYPE_SHARE_PIC_TO_WX = 66;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_C2C = 6;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_DEVICE = 19;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_DISUSS = 17;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_FORWARD = 20;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_GUILD = 67;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_THUMB_C2C = 7;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_THUMB_DISUSS = 18;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_THUMB_GUILD = 68;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_THUMB_TROOP = 16;
    public static final int TRANSFILE_TYPE_SHORT_VIDEO_TROOP = 9;
    public static final int TRANSFILE_TYPE_SM_LONGMESSAGE = 131079;
    public static final int TRANSFILE_TYPE_STAR_PHOTO = 50;
    public static final int TRANSFILE_TYPE_STAR_PHOTO_THUMBNAIL = 51;
    public static final int TRANSFILE_TYPE_STRUCT_SHARE = 52;
    public static final int TRANSFILE_TYPE_THEME = 131072;
    public static final int TRANSFILE_TYPE_TRIBE_UGC_VIDEO = 327681;
    public static final int TRANSFILE_TYPE_TROOP_EFFECT_PIC = 55;
    public static final int TRANSFILE_TYPE_UFDOWNLOAD_FILE = 5;
    public static final int TRANSFILE_TYPE_URL = 131076;
    public static final int TRANSFILE_TYPE_VIDEO = 3;
    public static final int TRANSFILE_TYPE_VOICE_SEARCH_SILK = 53;
    public static final int TRANSFILE_TYPE_ZPLAN_CDN_AVATAR = 71;
    public static final int TRANSFILE_TYPE_ZPLAN_CDN_IMAGE = 70;
    public static final int TRANSFILE_TYPE_ZPLAN_CDN_MOD = 72;
    public static final int TRANSFILE_TYPE_ZPLAN_USER_IMAGE = 69;

    public static final int TYPE_RECV = 1;
    public static final int TYPE_RECV_ONLINE = 2;
    public static final int TYPE_SEND = 0;
    public static final int UIN_BUDDY = 0;
    public static final int UIN_DISCUSS = 2;
    public static final int UIN_TROOP = 1;

    public String domain;
    public String downDomain;
    public long endTime;
    public int errorCode;
    public String errorMessage;
    public File file;
    public long fileID;
    public String fileKey;
    public String fileMd5;
    public String filePath;
    public long fileSize;
    public int fileType;
    public String fileUrl;
    public String forwardTaskKey;
    public String friendUin;
    public int isRead;
    public boolean isStreamMode;
    public int lastStatus;
    public byte[] localFileMd5;
    public String logTag;
    public long mSecMsgId;
    public long mSubMsgId;
    public String mUin;
    public String msgImageData;
    public String msgTime;
    public String orgiDownUrl;
    public String peerUin;
    public int picScale;
    public long picThumbSize;
    public BaseTransProcessor processor;
    public boolean processorDoReportSelf;
    public int pttSlicePos;
    public String pttSliceText;
    public OutputStream revStream;
    public String selfUin;
    public InputStream sendStream;
    public String serverPath;
    public long startTime;
    public int status;
    public long stepUrlCost;
    public String suffixType;
    public String thumbDownUrl;
    public String thumbPath;
    public String thumbUrl;
    public String tmpFilePath;
    public byte[] transferData;
    public long transferedSize;
    public String uKey;
    public int uinType;
    public long uniseq;
    public String[] urls;
    public byte[] userInfo;
    public String uuidPath;
}
