package tencent.im.oidb.cmd0x5eb;

import com.tencent.mobileqq.pb.ByteStringMicro;
import com.tencent.mobileqq.pb.MessageMicro;
import com.tencent.mobileqq.pb.PBBytesField;
import com.tencent.mobileqq.pb.PBField;
import com.tencent.mobileqq.pb.PBStringField;
import com.tencent.mobileqq.pb.PBUInt32Field;
import com.tencent.mobileqq.pb.PBUInt64Field;

public class oidb_0x5eb  {
    public static final class UdcUinData extends MessageMicro<UdcUinData> {
        public final PBBytesField bytes_basic_cli_flag;
        public final PBBytesField bytes_basic_svr_flag;
        public final PBBytesField bytes_birthday;
        public final PBBytesField bytes_city;
        public final PBBytesField bytes_city_id;
        public final PBBytesField bytes_country;
        public final PBBytesField bytes_full_age;
        public final PBBytesField bytes_full_birthday;
        public final PBBytesField bytes_mss1_service;
        public final PBBytesField bytes_mss2_identity;
        public final PBBytesField bytes_mss3_bitmapextra;
        public final PBBytesField bytes_music_gene;
        public final PBBytesField bytes_nick;
        public final PBBytesField bytes_openid;
        public final PBBytesField bytes_province;
        public final PBBytesField bytes_req_vip_ext_id;
        public final PBBytesField bytes_stranger_declare;
        public final PBBytesField bytes_stranger_nick;
        public final PBUInt32Field int32_history_num_flag;
        public final PBUInt32Field roam_flag_qq_7day;
        public final PBUInt32Field roam_flag_svip_2year;
        public final PBUInt32Field roam_flag_svip_5year;
        public final PBUInt32Field roam_flag_svip_forever;
        public final PBUInt32Field roam_flag_vip_30day;
        public final PBStringField str_zplanphoto_url;
        public final PBUInt32Field uint32_400_flag;
        public final PBUInt32Field uint32_age;
        public final PBUInt32Field uint32_allow;
        public final PBUInt32Field uint32_alphabetic_font_flag;
        public final PBUInt32Field uint32_apollo_status;
        public final PBUInt32Field uint32_apollo_timestamp;
        public final PBUInt32Field uint32_apollo_vip_flag;
        public final PBUInt32Field uint32_apollo_vip_level;
        public final PBUInt32Field uint32_auth_flag;
        public final PBUInt32Field uint32_auto_to_text_flag;
        public final PBUInt32Field uint32_bubble_id;
        public final PBUInt32Field uint32_bubble_unread_switch;
        public final PBUInt32Field uint32_business_user;
        public final PBUInt32Field uint32_c2c_aio_shortcut_switch;
        public final PBUInt32Field uint32_charm;
        public final PBUInt32Field uint32_charm_level;
        public final PBUInt32Field uint32_charm_shown;
        public final PBUInt32Field uint32_city_zone_id;
        public final PBUInt32Field uint32_cmshow_3d_flag;
        public final PBUInt32Field uint32_common_place1;
        public final PBUInt32Field uint32_constellation;
        public final PBUInt32Field uint32_dance_max_score;
        public final PBUInt32Field uint32_default_cover_in_use;
        public final PBUInt32Field uint32_do_not_disturb_mode_time;
        public final PBUInt32Field uint32_elder_mode_flag;
        public final PBUInt32Field uint32_ext_flag;
        public final PBUInt32Field uint32_extend_friend_card_shown;
        public final PBUInt32Field uint32_extend_friend_flag;
        public final PBUInt32Field uint32_extend_friend_switch;
        public final PBUInt32Field uint32_face_id;
        public final PBUInt32Field uint32_file_assist_top;
        public final PBUInt32Field uint32_flag_color_note_recent_switch;
        public final PBUInt32Field uint32_flag_hide_pretty_group_owner_identity;
        public final PBUInt32Field uint32_flag_is_pretty_group_owner;
        public final PBUInt32Field uint32_flag_kid_mode_can_pull_group;
        public final PBUInt32Field uint32_flag_kid_mode_can_search_by_strangers;
        public final PBUInt32Field uint32_flag_kid_mode_can_search_friends;
        public final PBUInt32Field uint32_flag_kid_mode_need_phone_verify;
        public final PBUInt32Field uint32_flag_kid_mode_switch;
        public final PBUInt32Field uint32_flag_qcircle_cover_switch;
        public final PBUInt32Field uint32_flag_school_verified;
        public final PBUInt32Field uint32_flag_study_mode_student;
        public final PBUInt32Field uint32_flag_study_mode_switch;
        public final PBUInt32Field uint32_flag_super_yellow_diamond;
        public final PBUInt32Field uint32_flag_use_mobile_net_switch;
        public final PBUInt32Field uint32_flag_zplan_edit_avatar;
        public final PBUInt32Field uint32_forbid_flag;
        public final PBUInt32Field uint32_freshnews_notify_flag;
        public final PBUInt32Field uint32_gender;
        public final PBUInt32Field uint32_global_group_level;
        public final PBUInt32Field uint32_god_flag;
        public final PBUInt32Field uint32_god_forbid;
        public final PBUInt32Field uint32_group_mem_credit_flag;
        public final PBUInt32Field uint32_guild_gray_flag;
        public final PBUInt32Field uint32_has_close_leba_youth_mode_plugin;
        public final PBUInt32Field uint32_hidden_session_switch;
        public final PBUInt32Field uint32_hidden_session_video_switch;
        public final PBUInt32Field uint32_input_status_flag;
        public final PBUInt32Field uint32_lang1;
        public final PBUInt32Field uint32_lang2;
        public final PBUInt32Field uint32_lang3;
        public final PBUInt32Field uint32_lflag;
        public final PBUInt32Field uint32_lightalk_switch;
        public final PBUInt32Field uint32_love_status;
        public final PBUInt32Field uint32_mss_update_time;
        public final PBUInt32Field uint32_music_ring_autoplay;
        public final PBUInt32Field uint32_music_ring_redpoint;
        public final PBUInt32Field uint32_music_ring_visible;
        public final PBUInt32Field uint32_normal_night_mode_flag;
        public final PBUInt32Field uint32_notify_on_like_ranking_list_flag;
        public final PBUInt32Field uint32_notify_partake_like_ranking_list_flag;
        public final PBUInt32Field uint32_oin;
        public final PBUInt32Field uint32_online_status_avatar_switch;
        public final PBUInt32Field uint32_plate_of_king_dan;
        public final PBUInt32Field uint32_plate_of_king_dan_display_switch;
        public final PBUInt32Field uint32_posterfont_id;
        public final PBUInt32Field uint32_preload_disable_flag;
        public final PBUInt32Field uint32_profession;
        public final PBUInt32Field uint32_profile_age_visible;
        public final PBUInt32Field uint32_profile_anonymous_answer_switch;
        public final PBUInt32Field uint32_profile_birthday_visible;
        public final PBUInt32Field uint32_profile_college_visible;
        public final PBUInt32Field uint32_profile_company_visible;
        public final PBUInt32Field uint32_profile_constellation_visible;
        public final PBUInt32Field uint32_profile_dressup_switch;
        public final PBUInt32Field uint32_profile_email_visible;
        public final PBUInt32Field uint32_profile_hometown_visible;
        public final PBUInt32Field uint32_profile_interest_switch;
        public final PBUInt32Field uint32_profile_life_achievement_switch;
        public final PBUInt32Field uint32_profile_location_visible;
        public final PBUInt32Field uint32_profile_membership_and_rank;
        public final PBUInt32Field uint32_profile_miniapp_switch;
        public final PBUInt32Field uint32_profile_music_switch;
        public final PBUInt32Field uint32_profile_musicbox_switch;
        public final PBUInt32Field uint32_profile_personal_note_visible;
        public final PBUInt32Field uint32_profile_personality_label_switch;
        public final PBUInt32Field uint32_profile_present_switch;
        public final PBUInt32Field uint32_profile_privilege;
        public final PBUInt32Field uint32_profile_profession_visible;
        public final PBUInt32Field uint32_profile_qqcard_switch;
        public final PBUInt32Field uint32_profile_qqcircle_switch;
        public final PBUInt32Field uint32_profile_sex_visible;
        public final PBUInt32Field uint32_profile_show_idol_switch;
        public final PBUInt32Field uint32_profile_splendid_switch;
        public final PBUInt32Field uint32_profile_sticky_note_offline;
        public final PBUInt32Field uint32_profile_sticky_note_switch;
        public final PBUInt32Field uint32_profile_weishi_switch;
        public final PBUInt32Field uint32_profile_wz_game_card_switch;
        public final PBUInt32Field uint32_profile_wz_game_skin_switch;
        public final PBUInt32Field uint32_pstn_c2c_call_time;
        public final PBUInt32Field uint32_pstn_c2c_last_guide_recharge_time;
        public final PBUInt32Field uint32_pstn_c2c_try_flag;
        public final PBUInt32Field uint32_pstn_c2c_vip;
        public final PBUInt32Field uint32_pstn_ever_c2c_vip;
        public final PBUInt32Field uint32_pstn_ever_multi_vip;
        public final PBUInt32Field uint32_pstn_multi_call_time;
        public final PBUInt32Field uint32_pstn_multi_last_guide_recharge_time;
        public final PBUInt32Field uint32_pstn_multi_try_flag;
        public final PBUInt32Field uint32_pstn_multi_vip;
        public final PBUInt32Field uint32_qq_assistant_switch;
        public final PBUInt32Field uint32_req_font_effect_id;
        public final PBUInt32Field uint32_req_global_ring_id;
        public final PBUInt32Field uint32_req_invite2group_auto_agree_flag;
        public final PBUInt32Field uint32_req_medalwall_flag;
        public final PBUInt32Field uint32_req_push_notice_flag;
        public final PBUInt32Field uint32_req_small_world_head_flag;
        public final PBUInt32Field uint32_rsp_connections_switch_id;
        public final PBUInt32Field uint32_rsp_listen_together_player_id;
        public final PBUInt32Field uint32_rsp_qq_level_icon_type;
        public final PBUInt32Field uint32_rsp_theme_font_id;
        public final PBUInt32Field uint32_school_status_flag;
        public final PBUInt32Field uint32_simple_ui_pref;
        public final PBUInt32Field uint32_simple_ui_switch;
        public final PBUInt32Field uint32_simple_update_time;
        public final PBUInt32Field uint32_stranger_vote_switch;
        public final PBUInt32Field uint32_subaccount_display_third_qq_flag;
        public final PBUInt32Field uint32_subscribe_nearbyassistant_switch;
        public final PBUInt32Field uint32_suspend_effect_id;
        public final PBUInt32Field uint32_sync_C2C_message_switch;
        public final PBUInt32Field uint32_torch_disable_flag;
        public final PBUInt32Field uint32_torchbearer_flag;
        public final PBUInt32Field uint32_troop_honor_rich_flag;
        public final PBUInt32Field uint32_troop_lucky_character_switch;
        public final PBUInt32Field uint32_troophonor_switch;
        public final PBUInt32Field uint32_vas_colorring_id;
        public final PBUInt32Field uint32_vas_diy_font_timestamp;
        public final PBUInt32Field uint32_vas_emoticon_usage_info;
        public final PBUInt32Field uint32_vas_face_id;
        public final PBUInt32Field uint32_vas_font_id;
        public final PBUInt32Field uint32_vas_magicfont_flag;
        public final PBUInt32Field uint32_vas_pendant_diy_id;
        public final PBUInt32Field uint32_vas_praise_id;
        public final PBUInt32Field uint32_vas_voicebubble_id;
        public final PBUInt32Field uint32_vip_flag;
        public final PBUInt32Field uint32_zplan_add_frd;
        public final PBUInt32Field uint32_zplan_cmshow_month_active_user;
        public final PBUInt32Field uint32_zplan_master_show;
        public final PBUInt32Field uint32_zplan_message_notice_switch;
        public final PBUInt32Field uint32_zplan_open;
        public final PBUInt32Field uint32_zplan_operators_network_switch;
        public final PBUInt32Field uint32_zplan_profile_card_show;
        public final PBUInt32Field uint32_zplan_qzone_show;
        public final PBUInt32Field uint32_zplan_samestyle_asset_switch;
        public final PBUInt32Field uint32_zplan_samestyle_package_switch;
        public final PBUInt64Field uint64_face_addon_id;
        public final PBUInt64Field uint64_game_appid;
        public final PBUInt64Field uint64_game_last_login_time;
        public final PBUInt64Field uint64_uin = PBField.initUInt64(0);
        public final PBUInt32Field unit32_concise_mode_flag;
        public final PBUInt32Field unit32_hide_camera_emoticon_flag;
        public final PBUInt32Field unit32_hide_cm_show_emoticon_flag;
        public final PBUInt32Field unit32_online_state_praise_notify;
        public final PBBytesField zplan_appearanceKey;
        public final PBUInt32Field zplan_appearanceKey_time;
        public final PBUInt32Field zplan_avatar_gender;

        public UdcUinData() {
            ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
            this.bytes_openid = PBField.initBytes(byteStringMicro);
            this.bytes_nick = PBField.initBytes(byteStringMicro);
            this.uint32_gender = PBField.initUInt32(0);
            this.uint32_allow = PBField.initUInt32(0);
            this.uint32_face_id = PBField.initUInt32(0);
            this.uint32_common_place1 = PBField.initUInt32(0);
            this.bytes_birthday = PBField.initBytes(byteStringMicro);
            this.bytes_full_birthday = PBField.initBytes(byteStringMicro);
            this.bytes_full_age = PBField.initBytes(byteStringMicro);
            this.bytes_country = PBField.initBytes(byteStringMicro);
            this.bytes_province = PBField.initBytes(byteStringMicro);
            this.bytes_city = PBField.initBytes(byteStringMicro);
            this.uint32_constellation = PBField.initUInt32(0);
            this.bytes_city_id = PBField.initBytes(byteStringMicro);
            this.uint32_city_zone_id = PBField.initUInt32(0);
            this.uint32_lang1 = PBField.initUInt32(0);
            this.uint32_lang2 = PBField.initUInt32(0);
            this.uint32_lang3 = PBField.initUInt32(0);
            this.uint32_age = PBField.initUInt32(0);
            this.uint32_oin = PBField.initUInt32(0);
            this.uint32_simple_update_time = PBField.initUInt32(0);
            this.uint32_group_mem_credit_flag = PBField.initUInt32(0);
            this.uint64_face_addon_id = PBField.initUInt64(0L);
            this.uint32_bubble_id = PBField.initUInt32(0);
            this.uint32_suspend_effect_id = PBField.initUInt32(0);
            this.bytes_music_gene = PBField.initBytes(byteStringMicro);
            this.uint32_lflag = PBField.initUInt32(0);
            this.uint32_ext_flag = PBField.initUInt32(0);
            this.bytes_basic_svr_flag = PBField.initBytes(byteStringMicro);
            this.bytes_basic_cli_flag = PBField.initBytes(byteStringMicro);
            this.bytes_mss1_service = PBField.initBytes(byteStringMicro);
            this.bytes_mss2_identity = PBField.initBytes(byteStringMicro);
            this.bytes_mss3_bitmapextra = PBField.initBytes(byteStringMicro);
            this.uint32_mss_update_time = PBField.initUInt32(0);
            this.uint32_lightalk_switch = PBField.initUInt32(0);
            this.bytes_stranger_nick = PBField.initBytes(byteStringMicro);
            this.bytes_stranger_declare = PBField.initBytes(byteStringMicro);
            this.uint32_love_status = PBField.initUInt32(0);
            this.uint32_profession = PBField.initUInt32(0);
            this.uint32_vip_flag = PBField.initUInt32(0);
            this.uint32_auth_flag = PBField.initUInt32(0);
            this.uint32_forbid_flag = PBField.initUInt32(0);
            this.uint32_god_forbid = PBField.initUInt32(0);
            this.uint32_god_flag = PBField.initUInt32(0);
            this.uint32_charm = PBField.initUInt32(0);
            this.uint32_charm_level = PBField.initUInt32(0);
            this.uint32_charm_shown = PBField.initUInt32(0);
            this.uint32_music_ring_visible = PBField.initUInt32(0);
            this.uint32_music_ring_autoplay = PBField.initUInt32(0);
            this.uint32_music_ring_redpoint = PBField.initUInt32(0);
            this.uint32_freshnews_notify_flag = PBField.initUInt32(0);
            this.uint32_subscribe_nearbyassistant_switch = PBField.initUInt32(0);
            this.uint32_apollo_vip_flag = PBField.initUInt32(0);
            this.uint32_apollo_vip_level = PBField.initUInt32(0);
            this.uint32_apollo_status = PBField.initUInt32(0);
            this.uint32_apollo_timestamp = PBField.initUInt32(0);
            this.uint32_pstn_c2c_vip = PBField.initUInt32(0);
            this.uint32_pstn_multi_vip = PBField.initUInt32(0);
            this.uint32_pstn_c2c_call_time = PBField.initUInt32(0);
            this.uint32_pstn_multi_call_time = PBField.initUInt32(0);
            this.uint32_pstn_c2c_try_flag = PBField.initUInt32(0);
            this.uint32_pstn_multi_try_flag = PBField.initUInt32(0);
            this.uint32_pstn_ever_c2c_vip = PBField.initUInt32(0);
            this.uint32_pstn_ever_multi_vip = PBField.initUInt32(0);
            this.uint32_pstn_multi_last_guide_recharge_time = PBField.initUInt32(0);
            this.uint32_pstn_c2c_last_guide_recharge_time = PBField.initUInt32(0);
            this.uint32_torchbearer_flag = PBField.initUInt32(0);
            this.uint32_torch_disable_flag = PBField.initUInt32(0);
            this.uint32_preload_disable_flag = PBField.initUInt32(0);
            this.uint32_notify_on_like_ranking_list_flag = PBField.initUInt32(0);
            this.uint32_vas_font_id = PBField.initUInt32(0);
            this.uint32_vas_diy_font_timestamp = PBField.initUInt32(0);
            this.uint32_vas_magicfont_flag = PBField.initUInt32(0);
            this.uint32_vas_colorring_id = PBField.initUInt32(0);
            this.uint32_vas_praise_id = PBField.initUInt32(0);
            this.uint32_global_group_level = PBField.initUInt32(0);
            this.uint32_req_invite2group_auto_agree_flag = PBField.initUInt32(0);
            this.uint32_subaccount_display_third_qq_flag = PBField.initUInt32(0);
            this.uint32_notify_partake_like_ranking_list_flag = PBField.initUInt32(0);
            this.int32_history_num_flag = PBField.initUInt32(0);
            this.roam_flag_qq_7day = PBField.initUInt32(0);
            this.roam_flag_vip_30day = PBField.initUInt32(0);
            this.roam_flag_svip_forever = PBField.initUInt32(0);
            this.roam_flag_svip_5year = PBField.initUInt32(0);
            this.roam_flag_svip_2year = PBField.initUInt32(0);
            this.uint64_game_appid = PBField.initUInt64(0L);
            this.uint64_game_last_login_time = PBField.initUInt64(0L);
            this.uint32_vas_voicebubble_id = PBField.initUInt32(0);
            this.uint32_vas_pendant_diy_id = PBField.initUInt32(0);
            this.uint32_vas_face_id = PBField.initUInt32(0);
            this.uint32_plate_of_king_dan = PBField.initUInt32(0);
            this.uint32_plate_of_king_dan_display_switch = PBField.initUInt32(0);
            this.uint32_vas_emoticon_usage_info = PBField.initUInt32(0);
            this.uint32_do_not_disturb_mode_time = PBField.initUInt32(0);
            this.uint32_dance_max_score = PBField.initUInt32(0);
            this.uint32_req_font_effect_id = PBField.initUInt32(0);
            this.bytes_req_vip_ext_id = PBField.initBytes(byteStringMicro);
            this.uint32_extend_friend_flag = PBField.initUInt32(0);
            this.uint32_posterfont_id = PBField.initUInt32(0);
            this.uint32_req_push_notice_flag = PBField.initUInt32(0);
            this.uint32_stranger_vote_switch = PBField.initUInt32(0);
            this.uint32_cmshow_3d_flag = PBField.initUInt32(0);
            this.uint32_input_status_flag = PBField.initUInt32(0);
            this.uint32_alphabetic_font_flag = PBField.initUInt32(0);
            this.uint32_has_close_leba_youth_mode_plugin = PBField.initUInt32(0);
            this.uint32_auto_to_text_flag = PBField.initUInt32(0);
            this.uint32_school_status_flag = PBField.initUInt32(0);
            this.uint32_simple_ui_switch = PBField.initUInt32(0);
            this.uint32_simple_ui_pref = PBField.initUInt32(0);
            this.uint32_hidden_session_switch = PBField.initUInt32(0);
            this.uint32_hidden_session_video_switch = PBField.initUInt32(0);
            this.uint32_bubble_unread_switch = PBField.initUInt32(0);
            this.uint32_req_global_ring_id = PBField.initUInt32(0);
            this.uint32_flag_is_pretty_group_owner = PBField.initUInt32(0);
            this.uint32_flag_hide_pretty_group_owner_identity = PBField.initUInt32(0);
            this.uint32_rsp_listen_together_player_id = PBField.initUInt32(0);
            this.uint32_rsp_connections_switch_id = PBField.initUInt32(0);
            this.uint32_rsp_qq_level_icon_type = PBField.initUInt32(0);
            this.uint32_flag_color_note_recent_switch = PBField.initUInt32(0);
            this.uint32_rsp_theme_font_id = PBField.initUInt32(0);
            this.uint32_flag_super_yellow_diamond = PBField.initUInt32(0);
            this.uint32_troophonor_switch = PBField.initUInt32(0);
            this.uint32_troop_lucky_character_switch = PBField.initUInt32(0);
            this.uint32_flag_school_verified = PBField.initUInt32(0);
            this.uint32_flag_study_mode_switch = PBField.initUInt32(0);
            this.uint32_flag_study_mode_student = PBField.initUInt32(0);
            this.uint32_flag_kid_mode_switch = PBField.initUInt32(0);
            this.uint32_flag_kid_mode_need_phone_verify = PBField.initUInt32(0);
            this.uint32_flag_kid_mode_can_search_friends = PBField.initUInt32(0);
            this.uint32_flag_kid_mode_can_pull_group = PBField.initUInt32(0);
            this.uint32_flag_kid_mode_can_search_by_strangers = PBField.initUInt32(0);
            this.uint32_400_flag = PBField.initUInt32(0);
            this.uint32_business_user = PBField.initUInt32(0);
            this.uint32_profile_sex_visible = PBField.initUInt32(0);
            this.uint32_profile_age_visible = PBField.initUInt32(0);
            this.uint32_profile_birthday_visible = PBField.initUInt32(0);
            this.uint32_profile_constellation_visible = PBField.initUInt32(0);
            this.uint32_profile_profession_visible = PBField.initUInt32(0);
            this.uint32_profile_college_visible = PBField.initUInt32(0);
            this.uint32_profile_location_visible = PBField.initUInt32(0);
            this.uint32_profile_hometown_visible = PBField.initUInt32(0);
            this.uint32_profile_email_visible = PBField.initUInt32(0);
            this.uint32_profile_personal_note_visible = PBField.initUInt32(0);
            this.uint32_profile_company_visible = PBField.initUInt32(0);
            this.uint32_req_medalwall_flag = PBField.initUInt32(0);
            this.uint32_profile_personality_label_switch = PBField.initUInt32(0);
            this.uint32_profile_life_achievement_switch = PBField.initUInt32(0);
            this.uint32_profile_interest_switch = PBField.initUInt32(0);
            this.uint32_profile_music_switch = PBField.initUInt32(0);
            this.uint32_profile_present_switch = PBField.initUInt32(0);
            this.uint32_profile_miniapp_switch = PBField.initUInt32(0);
            this.uint32_profile_musicbox_switch = PBField.initUInt32(0);
            this.uint32_profile_sticky_note_switch = PBField.initUInt32(0);
            this.uint32_profile_sticky_note_offline = PBField.initUInt32(0);
            this.uint32_profile_qqcircle_switch = PBField.initUInt32(0);
            this.uint32_profile_weishi_switch = PBField.initUInt32(0);
            this.uint32_extend_friend_card_shown = PBField.initUInt32(0);
            this.uint32_extend_friend_switch = PBField.initUInt32(0);
            this.uint32_profile_anonymous_answer_switch = PBField.initUInt32(0);
            this.uint32_profile_wz_game_card_switch = PBField.initUInt32(0);
            this.uint32_troop_honor_rich_flag = PBField.initUInt32(0);
            this.uint32_profile_splendid_switch = PBField.initUInt32(0);
            this.uint32_profile_membership_and_rank = PBField.initUInt32(0);
            this.uint32_profile_privilege = PBField.initUInt32(0);
            this.uint32_c2c_aio_shortcut_switch = PBField.initUInt32(0);
            this.uint32_qq_assistant_switch = PBField.initUInt32(0);
            this.uint32_profile_show_idol_switch = PBField.initUInt32(0);
            this.uint32_file_assist_top = PBField.initUInt32(0);
            this.uint32_guild_gray_flag = PBField.initUInt32(0);
            this.uint32_elder_mode_flag = PBField.initUInt32(0);
            this.zplan_appearanceKey_time = PBField.initUInt32(0);
            this.zplan_appearanceKey = PBField.initBytes(byteStringMicro);
            this.unit32_concise_mode_flag = PBField.initUInt32(0);
            this.unit32_hide_cm_show_emoticon_flag = PBField.initUInt32(0);
            this.unit32_hide_camera_emoticon_flag = PBField.initUInt32(0);
            this.uint32_zplan_open = PBField.initUInt32(0);
            this.uint32_zplan_add_frd = PBField.initUInt32(0);
            this.uint32_zplan_qzone_show = PBField.initUInt32(0);
            this.uint32_zplan_master_show = PBField.initUInt32(0);
            this.uint32_zplan_profile_card_show = PBField.initUInt32(0);
            this.uint32_zplan_samestyle_asset_switch = PBField.initUInt32(0);
            this.uint32_zplan_samestyle_package_switch = PBField.initUInt32(0);
            this.uint32_zplan_operators_network_switch = PBField.initUInt32(0);
            this.uint32_zplan_message_notice_switch = PBField.initUInt32(0);
            this.str_zplanphoto_url = PBField.initString("");
            this.uint32_normal_night_mode_flag = PBField.initUInt32(0);
            this.zplan_avatar_gender = PBField.initUInt32(0);
            this.uint32_zplan_cmshow_month_active_user = PBField.initUInt32(0);
            this.unit32_online_state_praise_notify = PBField.initUInt32(0);
            this.uint32_flag_use_mobile_net_switch = PBField.initUInt32(0);
            this.uint32_flag_zplan_edit_avatar = PBField.initUInt32(0);
            this.uint32_default_cover_in_use = PBField.initUInt32(0);
            this.uint32_flag_qcircle_cover_switch = PBField.initUInt32(0);
            this.uint32_req_small_world_head_flag = PBField.initUInt32(0);
            this.uint32_online_status_avatar_switch = PBField.initUInt32(0);
            this.uint32_profile_wz_game_skin_switch = PBField.initUInt32(0);
            this.uint32_sync_C2C_message_switch = PBField.initUInt32(0);
            this.uint32_profile_dressup_switch = PBField.initUInt32(0);
            this.uint32_profile_qqcard_switch = PBField.initUInt32(0);
        }
    }
}