package SummaryCard;

import com.qq.jce.JceStruct;

import java.util.ArrayList;
import java.util.Map;

import QQService.VipBaseInfo;

public final class RespSummaryCard extends JceStruct {
    public byte bAge;
    public short bAvailVoteCnt;
    public short bHaveVotedCnt;
    public byte bSex;
    public byte bValid4Vote;
    public int eAddOption;
    public int i0x6d4Success;
    public int iBirthday;
    public int iContactNotBindQQ;
    public int iFace;
    public int iLastestVoteCount;
    public int iLevel;
    public int iPhotoCount;
    public int iVoteCount;
    public long lCacheControl;
    public long lUIN;
    public long lUserFlag;
    public Map<String, String> mapQzoneEx;
    public AlbumInfo oLatestPhotos;
    public AddFrdSrcInfo stAddFrdSrcInfo;
    public QQApolloInfo stApollo;
    public BindPhoneInfo stBindPhoneInfo;
    public TCampusCircleInfo stCampusCircleInfo;
    //public TCoverInfo stCoverInfo;
    public DateCard stDateCard;
    public VipBaseInfo stDiamonds;
    public TEIMInfo stEimInfo;
    public GiftInfo stGiftInfo;
    public HeartInfo stHeartInfo;
    public InterestTagInfo stInterestTag;
    //public TMedalWallInfo stMedalWallInfo;
    //public TNearbyGodInfo stNearbyGodInfo;
    //public TNowBroadcastInfo stNowBroadcastInfo;
    //public OlympicInfo stOlympicInfo;
    //public PanSocialInfo stPanSocialInfo;
    //public PrivilegeBaseInfo stPrivInfo;
    public QCallInfo stQCallInfo;
    public TQimInfo stQimInfo;
   // public QiqiVideoInfo stQiqiVideoInfo;
    public TTimInfo stTimInfo;
    //public UserFeed stUserFeed;
    //public TVideoHeadInfo stVideoHeadInfo;
    //public QQVideoInfo stVideoInfo;
    public VipBaseInfo stVipInfo;
    public VoiceInfo stVoiceInfo;
    //public WeishiInfo stWeishiInfo;
    public String strAutoRemark;
    public String strCity;
    public String strContactName;
    public String strCountry;
    public String strDiscussName;
    public String strEIMBindPhoneNum;
    public String strEIMId;
    public String strEmail;
    public String strGroupName;
    public String strGroupNick;
    public String strLoginDesc;
    public String strMobile;
    public String strNick;
    public String strPersonal;
    public String strProvince;
    public String strQzoneFeedsDesc;
    public String strQzoneHeader;
    public String strRemark;
    public String strRespMusicInfo;
    public String strShowName;
    public String strSign;
    public String strSpaceName;
    public String strStatus;
    public String strVoteLimitedNotice;
    public long uAccelerateMultiple;
    public long uCareer;
    public long uCurMulType;
    public long uFriendGroupId;
    public long uLoginDays;
    public long uQQMasterLoginDays;
    public long uRichCardNameVer;
    public long uSignModifyTime;
    public long uTemplateId;
    public long ulFaceAddonId;
    public long ulShowControl;
    public ArrayList<String> vAddQuestion;
    public byte[] vCommLabel;
    public byte[] vExtendCard;
    public byte[] vHotChatInfo;
    public byte[] vLongNickTopicInfo;
    public byte[] vNearbyTaskInfo;
    public byte[] vNowInfo;
    public ArrayList<TPraiseInfo> vPraiseList;
    public byte[] vQzoneCoverInfo;
    public byte[] vResp0x5ebInfo;
    public byte[] vRespCustomLabelInfo;
    public byte[] vRespKandianInfo;
    public byte[] vRespLastGameInfo;
    public byte[] vRespQQStoryInfo;
    public byte[] vRespStarInfo;
    public byte[] vRespTemplateInfo;
    public byte[] vRichSign;
    public byte[] vSeed;
    public byte[] vTempChatSig;
    public byte[] vVisitingCardInfo;
    public ArrayList<byte[]> vvRespServices;
    public ArrayList<byte[]> vvRespServicesBigOrder;
}