package com.tencent.qqnt.kernel.nativeinterface;



public enum SearchLocalInfoType {
    KSEARCHLOCALINFOTYPEUNKNOWN,
    KSEARCHLOCALINFOTYPEBUDDY,
    KSEARCHLOCALINFOTYPEGROUP,
    KSEARCHLOCALINFOTYPEMSG,
    KSEARCHLOCALINFOTYPEFILE
}
