package com.tencent.qqnt.kernel.nativeinterface;



public enum SearchLocalBusinessType {
    KSEARCHLOCALBUSINESSTYPEUNKNOWN,
    KSEARCHLOCALBUSINESSTYPEALL,
    KSEARCHLOCALBUSINESSTYPECREATEGROUP,
    KSEARCHLOCALBUSINESSTYPEFORWARD,
    KSEARCHLOCALBUSINESSTYPEDESKTOPALL,
    KSEARCHLOCALBUSINESSTYPEDESKTOPBUDDY,
    KSEARCHLOCALBUSINESSTYPEDESKTOPGROUP,
    KSEARCHLOCALBUSINESSTYPEMQQALL
}
