package com.tencent.qqnt.kernel.nativeinterface;



public enum SearchHistoryType {
    KSEARCHHISTORYTYPEUNKNOWN,
    KSEARCHHISTORYTYPEBUDDY,
    KSEARCHHISTORYTYPEGROUP,
    KSEARCHHISTORYTYPEMSG,
    KSEARCHHISTORYTYPEFILE
}
