package com.tencent.qqnt.kernel.nativeinterface;



public enum SearchGroupChatInfoSortType {
    KSEARCHGROUPCHATINFOSORTTYPEUNKNOWN,
    KSEARCHGROUPCHATINFOSORTTYPEDEFAULT,
    KSEARCHGROUPCHATINFOSORTTYPELATESTCREATE,
    KSEARCHGROUPCHATINFOSORTTYPEFEWMEMBER
}
